parameters:
  model_definition_root: '%TESTGEN_ROOT%/model_definitions'
  template_root: '%TESTGEN_ROOT%/templates'

services:
  model_builder:
    class: '\TestGen\model\ModelFactory'
  render_engine:
    class: '\TestGen\render\TwigEngine'
    arguments: ['%template_root%']
  testgen.generator:
    class: '\TestGen\generate\TestGenerator'
    arguments:
      - '@model_builder'
      - '@render_engine'
      - '%model_definition_root%'
      - '%template_root%'