parameters:
  model_root: '%TOZART_ROOT%/models'
  template_root: '%TOZART_ROOT%/templates'

services:
  filesystem:
    class: '\Tozart\os\FileSystemFactory'
  subject_factory:
    class: '\Tozart\Subject\SubjectFactory'
  subject_manager:
    class: '\Tozart\Subject\SubjectManager'
    arguments:
      - '@subject_factory'
  printer:
    class: '\Tozart\render\TwigPrinter'
    arguments: ['%template_root%']
  director:
    class: '\Tozart\Director'
    arguments:
      - '@subject_factory'
      - '@printer'
      - '%model_root%'
      - '%template_root%'