parameters:
  model_root: '%MODEL_ROOT%'
  template_root: '%TEMPLATE_ROOT%'

services:
  # File system
  file_system.parse.yaml:
    class: 'Tozart\os\parse\YamlParser'
  file_system.file_type.yaml:
    class: 'Tozart\os\FileType'
    arguments:
      - YAML
      - [yml, yaml]
      - '@file_system.parse.yaml'
    public: FALSE
  file_system.file_type.twig:
    class: 'Tozart\os\FileType'
    arguments:
      - TWIG
      - [twig]
    public: FALSE
  file_system:
    class: 'Tozart\os\FileSystem'
    arguments:
      - ['@file_system.file_type.yaml', '@file_system.file_type.twig']

  # Models
  model.discovery:
    class: 'Tozart\Discovery\ModelDiscovery'
    arguments:
      - ['%model_root%']
      - '@file_system.file_type.yaml'
  model.factory:
    class: 'Tozart\Model\ModelFactory'
    arguments:
      - '@model.discovery'
  model.manager:
    class: 'Tozart\Model\ModelManager'
    arguments:
      - '@model.factory'

  # Subjects
  subject.discovery:
    class: 'Tozart\Discovery\SubjectDiscovery'
    arguments:
      - []
      - '@file_system.file_type.yaml'
  subject.factory:
    class: 'Tozart\Subject\SubjectFactory'
    arguments:
      - '@subject.discovery'
      - '@model.manager'
  subject.manager:
    class: 'Tozart\Subject\SubjectManager'
    arguments:
      - '@subject.factory'

  # Templates
  render.template_discovery:
    class: 'Tozart\Discovery\TemplateDiscovery'
    arguments:
      - ['%template_root%']
      - '@file_system.file_type.twig'
  render.renderer:
    class: 'Tozart\render\TwigRenderer'