parameters:
  model_root: '%MODEL_ROOT%'
  template_root: '%TEMPLATE_ROOT%'

services:
  # File system
  file_system.parse.yaml:
    class: '\Tozart\os\parse\YamlParser'
  file_system.file_type.yaml:
    class: '\Tozart\os\FileType'
    arguments:
      - YAML
      - [yml, yaml]
      - '@file_system.parse.yaml'
    public: FALSE
  file_system:
    class: '\Tozart\os\FileSystem'
    arguments:
  file_system.parse.manager:
    class: '\Tozart\os\parse\FileParserManager'
      - ['@file_system.file_type.yaml']
    arguments:
      - '@file_system.parse.yaml'
  subject_factory:
    class: '\Tozart\Subject\SubjectFactory'
  subject_manager:
    class: '\Tozart\Subject\SubjectManager'
    arguments:
      - '@subject_factory'
  template_locator:
    class: '\Tozart\render\TemplateLocator'
    arguments:
      - ['%template_root%']
      - ['@id.@type.feature', '@type.feature']
  printer:
    class: '\Tozart\render\TwigPrinter'
    arguments: ['%template_root%']