parameters:
  model_root: '%TOZART_ROOT%/models'
  template_root: '%TOZART_ROOT%/templates'

services:
  file_system:
    class: '\Tozart\os\FileSystem'
  file_system.parse.manager:
    class: '\Tozart\os\parse\FileParserManager'
    arguments: []
  subject_factory:
    class: '\Tozart\Subject\SubjectFactory'
  subject_manager:
    class: '\Tozart\Subject\SubjectManager'
    arguments:
      - '@subject_factory'
  template_locator:
    class: '\Tozart\render\TemplateLocator'
    arguments:
      - ['%template_root%']
      - ['@id.@type.feature', '@type.feature']
  printer:
    class: '\Tozart\render\TwigPrinter'
    arguments: ['%template_root%']